name: payuung_pribadi_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # ICON
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.12.0

  # BLOC
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  hydrated_bloc:
  freezed_annotation: ^2.4.1

  # API REQUEST DEPENDENCY
  dio: ^5.4.0

  # IMAGE PICKER
  uuid: ^4.5.0
  image_picker: ^1.0.8
  path_provider:

  # LOCAL STORAGE
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # OTHERS
  flutter_config: ^2.0.0
  connectivity_plus: ^6.0.3
  permission_handler: ^11.3.1
  flutter_svg:
  flutter_bottom_drawer:
  easy_stepper:
  table_calendar: ^3.0.9
  intl:

dev_dependencies:
  flutter_lints: ^2.0.0
  very_good_analysis: ^3.1.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  hive_generator:
  freezed: ^2.5.2

flutter_config:
  path: ../

get_cli:
  sub_folder: false

flutter:
  assets:
    - assets/launcher_icon/
    - assets/vectors/

  uses-material-design: true
